---
- name: make sure poudriere is installed
  pkgng:
    name: "{{item}}"
    state: present
  with_items:
    - poudriere
    - rsync
  tags: poudriere

- name: install helpers for interactive usage
  pkgng:
    name: "{{item}}"
    state: present
  with_items:
    - vim-console
    - byobu
    - screen
    - fish
    - htop

- name: make sure work zpool is modern enough
  command: zpool upgrade tank
  tags: poudriere

- name: ensure key directory
  file:
    dest: /usr/local/etc/ssl/keys
    mode: 0700
    owner: root
    group: wheel 
    state: directory
  tags: poudriere

  # expected to be available locally outside this repo
- name: upload poudriere signing key
  copy:
    src: ../../../../../files/poudriere.key
    dest: /usr/local/etc/ssl/keys/poudriere.key
    mode: 0600
    owner: root
    group: wheel 
  tags: poudriere

- name: poudriere configuration
  template:
    src: poudriere.conf.j2
    dest: /usr/local/etc/poudriere.conf
  tags: 
    - poudriere
    - poudriere-conf

- name: create ports tree directories
  command: poudriere ports -c -p briefkasten
  args:
    creates: /usr/local/poudriere/ports/briefkasten
  tags: poudriere

- name: create build jail
  command: poudriere jail -c -j 111amd64 -v 11.1-RELEASE -a amd64
  args:
    creates: /usr/local/poudriere/jails/111amd64
  tags: poudriere

- name: configure build jail
  copy:
    src: 111amd64-make.conf
    dest: /usr/local/etc/poudriere.d/111amd64-make.conf
  tags: poudriere

- name: upload package options
  synchronize:
    src: 111amd64-briefkasten-options/
    dest: /usr/local/etc/poudriere.d/111amd64-briefkasten-options/
    rsync_opts:
      - "-e ploy-ssh"
      - "--delete"
      - "-av"
  tags:
    - poudriere

- name: upload package list
  copy:
    src: pkg_list
    dest: /usr/local/etc/poudriere.d/briefkasten-pkglist
  tags: poudriere

- name: create distfiles cache directory
  file:
    path: "{{ distfiles_cache }}"
    state: directory
  tags: poudriere
