---
- name: make sure poudriere is installed
  pkgng:
    name: poudriere
    state: present
  tags: poudriere

- name: poudriere configuration
  template:
    src: poudriere.conf.j2
    dest: /usr/local/etc/poudriere.conf
  tags: poudriere

- name: create ports tree directories
  command: poudriere ports -c -p briefkasten creates=/usr/local/poudriere/ports/briefkasten
  tags: poudriere

- name: create build jail
  command: poudriere jail -c -j 102amd64 -v 10.2-RELEASE -a amd64 creates=/usr/local/poudriere/jails/102amd64
  tags: poudriere

- name: configure build jail
  copy:
    src: 102amd64-make.conf
    dest: /usr/local/etc/poudriere.d/102amd64-make.conf
  tags: poudriere

- name: upload package list
  copy:
    src: pkg_list
    dest: /usr/local/etc/poudriere.d/briefkasten-pkglist
  tags: poudriere

- name: create distfiles cache directory
  file:
    path: "{{ distfiles_cache }}"
    state: directory
  tags: poudriere

- name: Ensure basejail etc exists
  file:
    path: "{{ jails_dir }}/newjail/etc/pkg"
    state: directory
  tags: poudriere

- name: Ensure pkgng configuration will be present in each jail
  copy:
    src: pkg_repo.conf
    dest: "{{ jails_dir }}/newjail/etc/pkg/FreeBSD.conf"
  tags: poudriere
