---
- name: ensure /etc/rc.conf.d exists
  file: path=/etc/rc.conf.d/ state=directory owner=root group=wheel mode=0655

- name: ensure helper packages are installed
  pkgng: name={{ item }} state=present
  with_items:
  - ezjail
  - sudo
  - screen
  - bash

- name: ensure ezjail is enabled on startup
  service: name=ezjail enabled=yes

- name: Base configuration of ezjail
  template: src=ezjail.conf.j2 dest=/usr/local/etc/ezjail.conf

- name: Install base jail
# we specifically install from the official freebsd host
# TODO: how to ensure integrity of the installed files?
  command: "ezjail-admin install -h ftp.FreeBSD.org creates={{ jails_dir }}/basejail/bin/ls"

