---
- name: ensure /etc/rc.conf.d exists
  file: path=/etc/rc.conf.d/ state=directory owner=root group=wheel mode=0655

- name: bind host sshd to primary ip
  lineinfile: dest=/etc/ssh/sshd_config state=present line='ListenAddress {{ ansible_all_ipv4_addresses[0] }}' create=yes
  # TODO: sshd is not actually restarted in RL
  notify:
    - restart sshd

# (re-)configure pkg properly after initial bootstrap
- name: pkg conf directory
  file: path=/etc/pkg state=directory

- name: pkg_repo.conf
  copy: src=pkg_repo.conf dest=/etc/pkg/

- name: pkg.conf
  copy: src=pkg.conf dest=/usr/local/etc/pkg.conf

- name: remove pkg.conf (contains deprecated value)
  file: path=/usr/local/etc/pkg.conf state=absent

- name: ensure helper packages are installed
  pkgng: name={{ item }} state=present
  with_items:
  - ezjail
  - sudo
  - screen
  - bash

- name: ensure ezjail is enabled on startup
  service: name=ezjail enabled=yes

- name: Base configuration of ezjail
  template: src=ezjail.conf.j2 dest=/usr/local/etc/ezjail.conf

- name: Install base jail
# we specifically install from the official freebsd host
# TODO: how to ensure integrity of the installed files?
  command: "ezjail-admin install -h ftp.FreeBSD.org creates={{ jails_dir }}/basejail/bin/ls"

- name: pkg.conf for newjail
  copy: src=pkg.conf dest={{ jails_dir }}/newjail/usr/local/etc/pkg.conf

- name: configure lo1
  lineinfile: dest=/etc/rc.conf state=present line='cloned_interfaces=lo1'

- name: configure lo1 aliases
  lineinfile: dest=/etc/rc.conf state=present line='ipv4_addrs_lo1=127.0.0.2-10/32'

- name: restart network
  command: sh -c 'ifconfig lo1 > /dev/null || ( service netif restart; service routing restart ; :); :'

- name: ensure the webserver jail exists
  ezjail: name=webserver ip_addr=192.168.2.117,127.0.0.2 disktype=zfs state=running

- name: let sshd in jail listen only on private ip
  lineinfile: dest={{ jails_dir }}/webserver/etc/ssh/sshd_config state=present line='ListenAddress 127.0.0.2'

- name: enable root ssh access in jail
  lineinfile: dest={{ jails_dir}}/webserver/etc/ssh/sshd_config state=present line='PermitRootLogin without-password' create=yes

- name: copy authorized_keys
  command: copy /root/.ssh/authorized_keys {{ jails_dir }}/webserver/root/.ssh/ creates={{ jails_dir }}/webserver/root/.ssh/authorized_keys

- name: enable sshd inside jail
  lineinfile: dest={{ jails_dir }}/webserver/etc/rc.conf state=present line='sshd_enable=YES' create=yes
  
- name: install packages for webserver
  pkgng_chroot: name={{ item }} jail="webserver" state=present
  with_items:
    - pkg
    - python27
    - nginx
  tags: webserver
