---
- name: create root data filesystem
  zfs:
    name: tank/data
    state: present
  tags:
    - zfs-layout

- name: create data filesystem
  zfs:
    name: tank/data/{{item}}
    state: present
  with_items:
    - shared
    - jails
  tags:
    - zfs-layout

- name: upgrade ZFS version
  command: zpool tank upgrade
  tags: zfs-layout 
