---
- hosts: briefkasten
  user: root
  tasks:
    - name: create jails
      command: "ezjail-admin start {{item}}"
      args:
        creates: "/usr/jails/{{item}}"
      with_items:
      - webserver
      - appserver
      - cleanser
      tags: jails

- hosts: briefkasten-webserver
  user: root
  roles:
    - { role: common, tags: ['common', 'webserver'] }
    - { role: webserver, tags: ['webserver'] }
- hosts: briefkasten-appserver
  user: root
  roles:
    - { role: common, tags: ['common', 'appserver'] }
    - { role: appserver, tags: ['appserver'] }

- hosts: briefkasten-cleanser
  user: root
  roles:
    - { role: common, tags: ['common', 'cleanser'] }
  tasks:
    - name: install packages
      pkgng: name={{ item }} state=present
      with_items:
      - zip
      - netpbm
      - ghostscript9-base
      - libreoffice

    - name: create cleanser user
      user: name=cleanser createhome=yes

    - name: create cleanser .ssh
      file: path=/usr/home/cleanser/.ssh owner=cleanser mode=700 state=directory

- hosts: briefkasten
  user: root
  tasks:
    # grant appserver's pyramid user ssh access
    - name: copy keyfile
      command: cp {{ jails_dir }}/appserver/usr/home/pyramid/.ssh/id_rsa.pub {{ jails_dir }}/cleanser/usr/home/cleanser/.ssh/authorized_keys creates={{ jails_dir }}/cleanser/usr/home/cleanser/.ssh/authorized_keys
    - name: copy ssh pub host key
      shell: sed -E -e 's:^:{{hostvars['briefkasten-cleanser']['ploy_ip']}} :' -e 's:[^ ]+$::' {{ jails_dir }}/cleanser/etc/ssh/ssh_host_rsa_key.pub > {{ jails_dir }}/appserver/usr/home/pyramid/.ssh/known_hosts creates={{ jails_dir }}/appserver/usr/home/pyramid/.ssh/known_hosts
    - name: fix permissions on keyfile
      command: chmod 600 {{ jails_dir }}/cleanser/usr/home/cleanser/.ssh/authorized_keys
    - name: fix permissions on known_hosts
      command: chmod 600 {{ jails_dir }}/appserver/usr/home/pyramid/.ssh/known_hosts

- hosts: briefkasten-appserver
  user: root
  tasks:
    - name: fix ownership of known_hosts
      command: chown pyramid /usr/home/pyramid/.ssh/known_hosts

- hosts: briefkasten-cleanser
  user: root
  tasks:
    - name: ensure ownership of scripts
      command: chown -R cleanser /usr/home/cleanser

    - name: Upload cleanser scripts
      copy: src=../application/middleware_scripts/ dest=/usr/local/bin/

