---
- hosts: cleanser
  user: root
  tasks:
  - name: install packages
    pkgng: name={{ item }} state=present
    with_items:
    - zip
    - netpbm
    - ghostscript9-nox11
    # - libreoffice

  - name: create cleanser user
    user: name=cleanser createhome=yes

  - name: create cleanser .ssh
    file: path=/usr/home/cleanser/.ssh owner=cleanser mode=700 state=directory

- hosts: vm-master
  user: root
  tasks:
    # grant appserver's pyramid user ssh access
    - name: copy keyfile
      command: cp {{ jails_dir }}/appserver/usr/home/pyramid/.ssh/id_rsa.pub {{ jails_dir }}/cleanser/usr/home/cleanser/.ssh/authorized_keys creates={{ jails_dir }}/cleanser/usr/home/cleanser/.ssh/authorized_keys
    - name: fix permissions on keyfile
      command: chmod 600 {{ jails_dir }}/cleanser/usr/home/cleanser/.ssh/authorized_keys

- hosts: cleanser
  user: root
  roles:
    - common
    - cleanser
