---

- name: install packages
  pkgng:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: configure nginx
  template:
    src: nginx.conf
    dest: /usr/local/etc/nginx/nginx.conf

- name: upload ssl certificate
  copy:
    src: "{{ cert_location }}"
    dest: /usr/local/etc/nginx/briefkasten.crt
  notify: restart nginx

- name: upload ssl key
  copy:
    src: "{{ key_location }}"
    dest: /usr/local/etc/nginx/briefkasten.key
  notify: restart nginx


- name: make sure nginx is running or reloaded
  service:
    name: nginx
    state: started
    enabled: true
