---
- name: make sure poudriere is installed
  pkgng: name=poudriere state=present

- name: poudriere configuration
  template: src=poudriere.conf.j2 dest=/usr/local/etc/poudriere.conf

- name: create ports tree
  command: poudriere ports -c creates=/usr/local/poudriere/ports/default/www/nginx/distinfo

- name: upload list of packages to build
  copy: src=pkg_list dest={{ pkg_list }}

- name: create build jail
  command: poudriere jail -c -j 92amd64 -v 9.2-RELEASE -a amd64 creates=/usr/local/poudriere/jails/92amd64

- name: configure build jail
  copy: src=92amd64-make.conf dest=/usr/local/etc/poudriere.d/92amd64-make.conf

- name: create distfiles cache directory
  file: path={{ distfiles_cache }} state=directory

- name: upload ports options
  copy: src=92amd64-options dest=/usr/local/etc/poudriere.d/

- name: start build run
  command: poudriere bulk -f {{ pkg_list }} -j 92amd64 creates={{ jails_dir }}/basejail/poudriere_data/packages/92amd64-default

- name: Ensure basejail etc exists
  file: path={{ jails_dir }}/newjail/etc/pkg state=directory

- name: Ensure pkgng configuration will be present in each jail
  copy: src=pkg_repo.conf dest={{ jails_dir }}/newjail//etc/pkg/pkg_repo.conf
