---
- name: make sure poudriere is installed
  pkgng: name=poudriere state=present

- name: poudriere configuration
  template: src=poudriere.conf.j2 dest=/usr/local/etc/poudriere.conf

- name: create ports tree directories
  command: poudriere ports -c -F creates=/usr/local/poudriere/ports/default

- name: create build jail
  command: poudriere jail -c -j 92amd64 -v 9.2-RELEASE -a amd64 creates=/usr/local/poudriere/jails/92amd64

- name: configure build jail
  copy: src=92amd64-make.conf dest=/usr/local/etc/poudriere.d/92amd64-make.conf

- name: create distfiles cache directory
  file: path={{ distfiles_cache }} state=directory

- name: Ensure basejail etc exists
  file: path={{ jails_dir }}/newjail/etc/pkg state=directory

- name: Ensure pkgng configuration will be present in each jail
  copy: src=pkg_repo.conf dest={{ jails_dir }}/newjail/etc/pkg/pkg_repo.conf
