---

- name: create application user
  # this creates /home/pyramid/.ssh/id_rsa{.pub}
  user: name={{appuser}} createhome=yes generate_ssh_key=yes

- name: configure supervisord
  template: src=supervisord.conf.j2 dest=/usr/local/etc/supervisord.conf

- name: enable supervisord at startup time
  lineinfile: dest=/etc/rc.conf state=present line='supervisord_enable=YES' create=yes

- name: make sure supervisord is running
  service: name=supervisord state=running
