---

- name: configure nginx
  template: src=nginx.conf.in dest=/usr/local/etc/nginx/nginx.conf

- name: make sure nginx is running
  service: name=nginx state=running

# TODO: make sure it's enabled at startup